### ISSUE TITLE
Handle sup tags

### ISSUE THREAD

**Issue by thinkelman-ESA** [hinkelman/chez-docs-scrape#5]
See `(doc "make-date" #t)` for `sup` example. With `sub`, the intent can hopefully still inferred, e.g., N<sub>t</sub> would become Nt, but 10<sup>9</sup> becomes 109.

**Comment by hinkelman** [comment]
Took the simple approach of replacing `sup` with `^` in commit [b0d1c4f](https://github.com/hinkelman/chez-docs-scrape/commit/b0d1c4fd3562b47721bcce4dc678d42a61ebed64).
